name: Update screenshots
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
      options: --user 1001
    steps:
      - name: Install git-lfs
        run: sudo apt install -y git-lfs
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # make sure to update .tool-versions as well!
          hugo-version: "0.147.3"
          extended: true
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Delete existing screenshots, in case a test has been deleted
        run: git rm --ignore-unmatch -r screenshots && rm -rf screenshots/*
      - name: Run Playwright tests
        run: pnpm exec playwright test --update-snapshots
      - name: Commit and push updated screenshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update screenshots'
